### PR TITLE
loading an ensemble from checkpoint

### PR DESCRIPTION
**Pull request by mttgdd**

### CODE REVIEW

**Comment by xuyxu** [comment]
Hi @mttgdd, thanks for this useful PR! Could you further check the code quality CI and fix some small problems on the coding style?

**Comment by mttgdd** [comment]
Of course, no problem. I'll work on those when I get a moment.

**Comment by xuyxu** [comment]
Great, thanks @mttgdd! After making some modifications to the documentation, I will merge this PR ;-)

**Comment by xuyxu** [comment]
Merged ;-)

**Pull request merged**
